<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <IsPackable>false</IsPackable>
    <PublishAot Condition="'$(Configuration)' == 'Release'">true</PublishAot>
    <TrimMode Condition="'$(Configuration)' == 'Release'">full</TrimMode>
    <StripSymbols Condition="'$(Configuration)' == 'Release'">true</StripSymbols>
    <NativeDebugSymbols Condition="'$(Configuration)' == 'Release'">false</NativeDebugSymbols>
    <IlcFoldIdenticalMethodBodies Condition="'$(Configuration)' == 'Release'">true</IlcFoldIdenticalMethodBodies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="ReactiveUI.Avalonia" />
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="ReactiveUI.SourceGenerators" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Avalonia.Diagnostics.Cdp\Avalonia.Diagnostics.Cdp.csproj" />
    <ProjectReference Include="..\..\src\Avalonia.Diagnostics.Cdp.Rdp\Avalonia.Diagnostics.Cdp.Rdp.csproj" />
    <ProjectReference Include="..\..\src\CDP.Rdp\CDP.Rdp.csproj" />
    <ProjectReference Include="..\..\src\CDP.Rdp.Rendering\CDP.Rdp.Rendering.csproj" />
    <ProjectReference Include="..\..\src\CDP.FluentNavigation\CDP.FluentNavigation.csproj" />
  </ItemGroup>
</Project>
