<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Chrome.DevTools.Protocol/Chrome.DevTools.Protocol.csproj" />
    <ProjectReference Include="../../src/Chrome.DevTools.Protocol.Automation/Chrome.DevTools.Protocol.Automation.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Fixtures/**/*.js" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
